config/routes.rb
Trimodal::Application.routes.draw do

  resources :contributors

  resources :fecund_corals

  resources :ss_corals

  resources :spawners

  resources :touches

  resources :people do
    resources :spawners
  end

  resources :fieldtrips do
    resources :observations
    resources :spawners
    resources :ss_corals
    resources :fecund_corals
  end

  resources :observations do
    resources :areas
  end

  resources :areas do
    resources :touches
  end

  resources :corals do
    resources :observations do
      resources :areas do
        resources :touches
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'contributors#new',      via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'


  # match 'export_touches' => 'corals#export_tagged', via: 'get'
  match 'export_tagged' => 'corals#export_tagged', via: 'get'
  match 'export_corals' => 'corals#export_corals', via: 'get'
  match 'export_spawners' => 'spawners#export_spawners', via: 'get'
  match 'export_size_structure' => 'ss_corals#export_size_structure', via: 'get'
  match 'export_fecundity' => 'fecund_corals#export_fecundity', via: 'get'

end

app/models/coral.rb
class Coral < ActiveRecord::Base
  
  validates :transect, :presence => true
  validates :map_x, :presence => true
  validates :map_y, :presence => true
  validates :species_code, :presence => true

  has_many :observations

  def self.search(search)
      if search
        where('species LIKE ? OR species_code LIKE ? OR notes LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
        # find(:all, :joins => :observations, :conditions => ['corals.species LIKE :search OR observations.tag_number LIKE :search', {:search => "%#{search}%"}])
      else
        all
      end
  end  
      
end

app/controllers/corals_controller.rb
class CoralsController < ApplicationController
  before_action :signed_in_contributor

  require 'open-uri'


  # GET /corals.json
  helper_method :sort_column, :sort_direction
  
  def index
    @corals = Coral.order(sort_column + " " + sort_direction).search(params[:search])
    @observations = Observation.all
    @areas = Area.all
      
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @corals }
    end
  end


  # GET /corals/1
  # GET /corals/1.json
  def show
    @coral = Coral.find(params[:id])
    @fieldtrips = Fieldtrip.all
    @areas = Area.all

    @files = Dir.glob("app/assets/images/tagged_raw_thumbs/*")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @coral }
    end
  end

  # GET /corals/new
  # GET /corals/new.json
  def new
    @coral = Coral.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @coral }
    end
  end

  # GET /corals/1/edit
  def edit
    @coral = Coral.find(params[:id])
  end

  # POST /corals
  # POST /corals.json
  def create
    @coral = Coral.new(coral_params)

    respond_to do |format|
      if @coral.save
        format.html { redirect_to @coral, flash: {success: 'Coral was successfully created.' } }
        format.json { render json: @coral, status: :created, location: @coral }
      else
        format.html { render action: "new" }
        format.json { render json: @coral.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /corals/1
  # PUT /corals/1.json
  def update
    @coral = Coral.find(params[:id])

    respond_to do |format|
      if @coral.update_attributes(coral_params)
        format.html { redirect_to @coral, flash: {success: 'Coral was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @coral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corals/1
  # DELETE /corals/1.json
  def destroy
    @coral = Coral.find(params[:id])
    @coral.destroy

    respond_to do |format|
      format.html { redirect_to corals_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def sort_column
    Coral.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def coral_params
    params.require(:coral).permit(:transect, :map_x, :map_y, :dim_1, :dim_2, :species, :species_code, :notes)
  end

  # t.integer  "transect"
  # t.integer  "map_x"
  # t.integer  "map_y"
  # t.integer  "dim_1"
  # t.integer  "dim_2"
  # t.string   "species"
  # t.string   "species_code"
  # t.text     "notes"
  
end

app/helpers/corals_helper.rb
module CoralsHelper
end

app/views/corals/_form.html.erb
<%= form_for(@coral) do |f| %>
  <%= render 'shared/error_messages', temp: @coral %>

  <div class="form-group">
    <%= f.label :transect %>
    <%= f.number_field :transect, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :map_x %>
    <%= f.number_field :map_x, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :map_y %>
    <%= f.number_field :map_y, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :dim_1 %>
    <%= f.number_field :dim_1, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :dim_2 %>
    <%= f.number_field :dim_2, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :species %>
	<%= f.select :species, ['', 'Acropora cytheria', 'Acropora fat dig', 'Acropora humilis', 'Acropora hyacinthus', 'Acropora intermedia', 'Acropora millepora', 'Acropora nasuta', 'Acropora spathulata', 'Acropora robusta', 'Goniastrea pectinata', 'Goniastrea retiformis'], class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :species_code %>
	<%= f.select :species_code, ['', 'AC', 'AD', 'AS', 'AH', 'AI', 'AM', 'AN', 'AL', 'AR', 'GP', 'GR'], class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, class: "form-control" %>
  </div>

    <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/corals/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <h2>Editing coral</h2>

    <%= render 'form' %>

    <%= link_to 'Back', corals_path %>
	</div>
</div>

app/views/corals/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">

    <h2>Tagged colonies</h2>

    <div class="well">
      <div class="row">
        <div class="col-md-6">
          <%= form_tag observations_path, :method => 'get' do %>
            <div class="input-group">
              <%= text_field_tag :osearch, params[:osearch], :placeholder => "Search observations (including tags)...", class: "form-control" %>
              <span class="input-group-btn">
                <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
              </span>
            </div>
          <% end %>
        </div>
      </div>

      <br/>

      <p>Download full dataset as <%= link_to 'CSV', '/export_tagged', :action => 'export_tagged', data: {turbolinks: false} %></p>
      <%= link_to 'New Coral', new_coral_path, class: "btn btn-default pull-right" %>
      <p>Download corals only as <%= link_to 'CSV', '/export_corals', :action => 'export_corals' %></p>
    </div>

    <div class="row">
      <div class="col-md-12">

        <% if @corals.empty? %>
          <h2> No matches</h2>
        <% else %>

        	<table class="table table-condensed">
            <thead>
          	  <tr>
          	    <th><%= sortable "id" %></th>
          	    <th><%= sortable "transect" %></th>
          	    <th>Species</th>
          	    <th><%= sortable "species_code" %></th>
          	    <th>Last tag</th>
          	    <th><%= sortable "notes" %></th>
                <th>Observations</th>
          	    <th></th>
          	  </tr>
          </thead>

        	<% @corals.each do |coral| %>
        	  <tbody>
              <tr>
          	    <td style="color:lightgrey"><%= coral.id %></td>
          	    <td><%= coral.transect %></td>
          	    <td><i><%= coral.species %></i></td>
          	    <!-- <td><%= coral.species %></td> -->
          	    <td><%= coral.species_code %></td>

          		<td><% if !coral.observations.empty? %>
          			<%= '%04d' % coral.observations.last.tag_number %>
          		<% end %></td>

          	    <td style='text-align:left; max-width:250px;'><%= coral.notes %></td>

                <td><%= coral.observations.size %></td>

                <td>
                  <div class="btn-group">
                    <%= link_to 'Show', coral, class: "btn btn-default" %>
                    <%= link_to 'Edit', edit_coral_path(coral), class: "btn btn-default" %>
                  </div>
                </td>
          	  </tr>
            </tbody>
        	<% end %>
        	</table>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/corals/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <h2>New coral</h2>

    <%= render 'form' %>

    <%= link_to 'Back', corals_path %>
	</div>
</div>

app/views/corals/show.html.erb
<div class="row">
  <div class="col-md-12">

		<h2>Tagged colony</h2>
		
		<table class="table">
			<tr class='top'>
			<td><table style="background-color: #444;"><tr class='image'>
				<% if !@coral.observations.blank? %>
					<% img = @coral.species_code + "%04d" % @coral.observations.last.tag_number + '_' + @coral.observations.last.fieldtrip.name_code + '_T' %>
					<% imgS = @coral.species_code + "%04d" % @coral.observations.last.tag_number + '_' + @coral.observations.last.fieldtrip.name_code + '_S' %>
					<% @temp = @files.find_all{|item| item.include? img }.last %>
					<% @tempS = @files.find_all{|item| item.include? imgS }.last %>
					
					<% if !@temp.nil? %>
						<td><%= link_to image_tag('tagged_raw_thumbs/' + @temp.split('/').last), image_path('tagged_raw/' + @temp.split('/').last.split('_tn').first + '.JPG') %>						
						</td></tr>
						<tr><td style="text-align:center;">
						<font color="white">(Latest image)</font>
					<% else %>
						<% if !@tempS.nil? %>
							<td><%= link_to image_tag('tagged_raw_thumbs/' + @tempS.split('/').last), image_path('tagged_raw/' + @tempS.split('/').last.split('_tn').first + '.JPG') %>
							</td></tr>
							<tr class='image'><td>
							<font color="white">(Latest image)</font>
						<% else %>
							<td style="height: 270px; width: 320px;"><font color="white">(The last observation has no images)</font>
						<% end %>
					<% end %>
					</td></tr>
				<% else %>
					<td style="height: 270px; width: 320px;"><font color="white">(The last observation has no images)</font>
				<% end %>
			</table></td>
			
			<td>
				<p>
				  <b>Species:</b> <i><%= @coral.species %></i>
				</p>

				<p><% if !@coral.observations.blank? %>
					<b>Current tag:</b> <span class="label label-primary"><%= @coral.species_code %><%= '%04d' % @coral.observations.last.tag_number %></span>
				</p><% end %>
				<p>
				  <b>Transect:</b>
				  <%= @coral.transect %> (x = <%= @coral.map_x %>, y = <%= @coral.map_y %>)
				</p>

				<p>
				  <b>Dimensions:</b> <%= @coral.dim_1 %>, <%= @coral.dim_2 %>
				</p>

				<p style="border:1px;">
				  <b>Colony notes:</b>
				  <font color="orange"><%= @coral.notes %></font>
				</p>
				<p>
		    	<%= link_to 'Edit coral', edit_coral_path(@coral), class: "btn btn-default" %>
		    </p>
			</td></tr>
		</table>


    <div class="row">
      <div class="col-md-6">
        <%= form_tag observations_path, :method => 'get' do %>
          <div class="input-group">
            <%= text_field_tag :osearch, params[:osearch], :placeholder => "Tag search...", class: "form-control" %>
            <span class="input-group-btn">
              <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
            </span>
          </div>
        <% end %>
      </div>
    </div>


		<h3>Tagged colony observations</h3>

		<a href="javascript:<% @coral.observations.each do |oo| %>jchange('div<%= oo.id %>')<% if oo != @coral.observations.last %>,<% end %><% end %>;">Show/hide all images</a>

		<table class="table table-condensed">
		<tr>
			<th></th>
			<th>Fieldtrip</th>
			<th>Mum</th>
			<th>Image tag</th>
			<th>Active tag</th>
			<th>Action</th>
			<th>Notes</th>
			<th>Areas</th>
			<th></th>
		</tr>

		<%= render @coral.observations.sort_by{|e| e[:fieldtrip_id]} %>

		<tr style='background-color:white;'>
			<% if !@coral.observations.blank? %>
				<% temp = @coral.observations.last.active_tag %>
				<% if temp.blank? %>	
					<% temp = @coral.observations.last.tag_number %>
				<% end %>		
			<% end %>
			
			<%= form_for([@coral, @coral.observations.build]) do |f| %>
			  <td></td>
			  <td><%= collection_select :observation, :fieldtrip_id, @fieldtrips, :id, :name_code, { :selected => @fieldtrips.last.id } %> </td>
			  <td><%= f.text_field :mother_id, :size => 6 %></td>
			  <td><%= f.text_field :tag_number, :value => temp, :size => 6 %></td>
			  <td><%= f.text_field :active_tag, :size => 6 %></td>
			  <td><%= f.select :action, ['', 'photographed', 'not found', 'no scale', 'not real', 'dead', 'gone'] %></td>
			  <td><%= f.text_field :notes %></td>
			  <td></td>
			  <td><%= f.submit class: "btn btn-primary" %></td>
			<% end %>
		</tr>
		</table>

		<br/>

	</div>
</div>