config/routes.rb
Trimodal::Application.routes.draw do

  resources :contributors

  resources :fecund_corals

  resources :ss_corals

  resources :spawners

  resources :touches

  resources :people do
    resources :spawners
  end

  resources :fieldtrips do
    resources :observations
    resources :spawners
    resources :ss_corals
    resources :fecund_corals
  end

  resources :observations do
    resources :areas
  end

  resources :areas do
    resources :touches
  end

  resources :corals do
    resources :observations do
      resources :areas do
        resources :touches
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'contributors#new',      via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'


  # match 'export_touches' => 'corals#export_tagged', via: 'get'
  match 'export_tagged' => 'corals#export_tagged', via: 'get'
  match 'export_corals' => 'corals#export_corals', via: 'get'
  match 'export_spawners' => 'spawners#export_spawners', via: 'get'
  match 'export_size_structure' => 'ss_corals#export_size_structure', via: 'get'
  match 'export_fecundity' => 'fecund_corals#export_fecundity', via: 'get'

end

app/models/area.rb
class Area < ActiveRecord::Base

  validates :outline_filename, :presence => true
  validates :outliner_name, :presence => true

  belongs_to :observation
  has_many :touches


end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :signed_in_contributor
  # GET /areas
  # GET /areas.json
  def index

    @coral = Coral.find(params[:coral_id])
    @observation = Observation.find(params[:observation_id])
    @areas = @observation.areas.find(params[:observation_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @areas }
    end
  end

  # GET /areas/1
  # GET /areas/1.json
  def show

    @area = Area.find(params[:id])
    @observation = Observation.find(params[:observation_id])
    @coral = Coral.find(params[:coral_id])

    @files = Dir.glob("app/assets/images/tagged_touch_thumbs/*")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/new
  # GET /areas/new.json
  def new

    @coral = Coral.find(params[:coral_id])
    @observation = Observation.find(params[:observation_id])
    @area = @coral.areas.create(params[:area])


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @area }
    end
  end

  # GET /areas/1/edit
  def edit

    @observation = Observation.find(params[:observation_id])
    @area = @observation.areas.find(params[:id])

  end

  # POST /areas
  # POST /areas.json
  def create

    @observation = Observation.find(params[:observation_id])
    @area = @observation.areas.create(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to coral_observation_path(@observation.coral, @observation), notice: 'The area was successfully created.' }
        format.json { render json: @area, status: :created, location: @area }
      else
        format.html { redirect_to coral_observation_path(@observation.coral, @observation), notice: '*The area was NOT created.  You must enter outliner name AND the outlined filename.' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /areas/1
  # PUT /areas/1.json
  def update
    @area = Area.find(params[:id])

    respond_to do |format|
      if @area.update_attributes(area_params)
        format.html { redirect_to coral_observation_path(@area.observation.coral, @area.observation), notice: 'Area was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy

    @observation = Observation.find(params[:observation_id])
    @area = @observation.areas.find(params[:id])

    @area.destroy

    respond_to do |format|
      format.html { redirect_to coral_observation_path(@observation.coral, @observation), notice: 'Area was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  private
  
  def area_params
    params.require(:area).permit(:observation_id, :outliner_name, :outline_filename, :area, :flag, :notes, :photographer_name, :acceptable, :acceptable_outline)
  end
  
  # t.integer  "observation_id"
  # t.string   "outliner_name"
  # t.string   "outline_filename"
  # t.decimal  "area"
  # t.boolean  "flag"
  # t.text     "notes"
  # t.datetime "created_at",         :null => false
  # t.datetime "updated_at",         :null => false
  # t.string   "photographer_name"
  # t.boolean  "acceptable"
  # t.boolean  "acceptable_outline"
  
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_area.html.erb
<tr>
	<td><a href="javascript:jchange('div<%= area.id %>');">Outlines</a></td>
<!-- 	<td style="color:lightgrey;"><%#= area.id %></td>
	<td style="color:lightgrey;"><%#= area.observation_id %></td>
	<td style="color:lightgrey;"><%#= area.observation.coral_id %></td>
 -->	<!-- <td><%#= area.photographer_name %></td> -->
	<td><%= area.outliner_name %></td>
  <td><%= area.outline_filename %></td>
	<td><% if !area.area.blank? %><%= '%.2f' % area.area %><% end %></td>
	<td><% if !area.perimeter.blank? %><%= '%.2f' % area.perimeter %><% end %></td>
	<td><%= area.flag %></td>
	<% if area.acceptable == false %>
	<td style="background-color: red;" ><%= area.acceptable %></td>
	<% else %>
	<td><%= area.acceptable %></td>
	<% end %>
	<% if area.acceptable_outline == false %>
	<td style="background-color: red;" ><%= area.acceptable_outline %></td>
	<% else %>
	<td><%= area.acceptable_outline %></td>
	<% end %>
  <!-- <td><%#= area.notes %></td> -->
	<td><%= area.touches.count %></td>
  
  <td>
    <div class="btn-group">
      <%= link_to 'Contacts', coral_observation_area_path(area.observation.coral, area.observation, area), class: "btn btn-default" %>
      <%= link_to 'Edit', edit_coral_observation_area_path(area.observation.coral, area.observation, area), class: "btn btn-default" %>
      <%= link_to 'Delete', coral_observation_area_path(area.observation.coral, area.observation, area), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-danger" %>
    </div>
  </td>

</tr>

<tr>
	<%# if area.flag %>
		<%# mid = area.outline_filename[(area.outline_filename.length-4)..area.outline_filename.length] %>
		<%# img = area.outline_filename[0..7] + "\.*_" + area.outliner_name %>
	    <%# @thumbs = @files.find_all{|item| item =~ /#{area.outline_filename[0..7]}.*#{mid}.*#{area.outliner_name}*/ } %>
	<%# else %>
		<% img = area.outline_filename + "_" + area.outliner_name %>
	    <% @thumbs = @files.find_all{|item| item.include? img } %>
	<%# end %>
	
    <td colspan=14>

	<table id="div<%= area.id %>" style="display:none;"><tr>

		<% @thumbs.each do |aa| %>

			<td style='padding:5px; background-color: white;'>
			<table style="background-color: #444;">
				<tr class='image'><td><%= image_tag 'tagged_outlines_thumbs/' + aa.split('/').last %></td></tr>
				<tr class='image'><td style="text-align:center;color:white;"><%= aa.split('/').last.split('_tn').first %></font></td></tr>
				<tr class='image'><td style="text-align:center;color:white;"><%= link_to 'OUTLINE', image_path('tagged_outlines/' + aa.split('/').last.split('_tn').first + '.jpeg'), :class => 'image' %></td></tr>
			
		</table>
		</td>		
	<% end %>
	
	
	</tr></table></td>

</tr>

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Observation: <%= @area.observation_id %></p>
  <div class="field">
    <%= f.label :photographer_name %>
    <%= f.text_field :photographer_name %>
  </div>
  <div class="field">
    <%= f.label :outliner_name %>
    <%= f.text_field :outliner_name %>
  </div>
  <div class="field">
    <%= f.label :outline_filename %>
    <%= f.text_field :outline_filename %>
  </div>
  <div class="field">
    <%= f.label :area %>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :perimeter %>
    <%= f.text_field :perimeter %>
  </div>
  <div class="field">
    <%= f.label :flag %>
    <%= f.check_box :flag %>
  </div>
  <div class="field">
    <%= f.label "Acceptable photo" %>
    <%= f.check_box :acceptable %>
  </div>
  <div class="field">
    <%= f.label :acceptable_outline %>
    <%= f.check_box :acceptable_outline %>
  </div>
  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn" %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<div class="row">
	<div class="span6 offset3">
    <h3>Editing area</h3>

    <%= render 'form' %>
  </div>
</div>

app/views/areas/index.html.erb
<h1>Listing areas</h1>

<%= @coral.id %>
<%= @observation.id %>

<table>
  <tr>
    <th>Observation</th>
    <th>Outliner name</th>
    <th>Outline filename</th>
    <th>Area</th>
    <th>Perimeter</th>
    <th>Flag</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @areas.each do |area| %>
  <tr>
    <td><%= area.observation %></td>
    <td><%= area.outliner_name %></td>
    <td><%= area.outline_filename %></td>
    <td><%= area.area %></td>
    <td><%= area.perimeter %></td>
    <td><%= area.flag %></td>
    <td><%= area.notes %></td>
    <td><%= link_to 'Show', area %></td>
    <td><%= link_to 'Edit', edit_area_path(area) %></td>
    <td><%= link_to 'Destroy', area, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Area', new_coral_observation_area_path(@area.observation, @area) %>

app/views/areas/new.html.erb
<h1>New area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<div class="row">
  <div class="col-md-12">

		<h2>Tagged colony observation outline</h2>

		<table class="table">
			<tr class='top'>
			<td>
				<table style="background-color: #444;"><tr class='image'>
					<% img = @area.outline_filename + '_' + @area.outliner_name %>
					<% @temp = @files.find_all{|item| item.include? img }.last %>
					<% if !@temp.nil? %>
					<td><%= link_to image_tag('tagged_touch_thumbs/' + @temp.split('/').last), image_path('tagged_touch/' + @temp.split('/').last.split('_tn').first + '.jpeg') %>
					</td></tr>
					<tr class='image'><td>
					<font color="white">(Latest image)</font>
					<% else %>
					<td style="height: 270px; width: 320px;"><font color="white">(The last observation has no images)</font>
					<% end %>
					</td></tr>
				</table>
			</td>

				<td>
				<p>
				  <b>Species:</b> <i><%= @coral.species %></i>
				  , <b>Tag:</b> <%= @coral.species_code %><%= '%03d' % @observation.tag_number %>
				  , <b>Fieldtrip:</b> F<%= @observation.fieldtrip_id %>
				</p>

				<p>
				  <b>Action:</b>
				  <%= @observation.action %>
				</p>

				<p>
				  <b>Outliner name:</b> <%= @area.outliner_name %>
				</p>
				<p>
					<b>Outline filename:</b> <%= @area.outline_filename %>
				</p>
				<p>
				  <b>Area:</b> <%= @area.area %>
				</p>
				<p>
				  <b>Perimeter:</b> <%= @area.perimeter %>
				</p>

				<p>
				  <b>Area notes:</b>
				  <font color="orange"><%= @area.notes %></font>
				</p>
				<p>
					<%= link_to 'Edit area', edit_coral_observation_area_path(@area.observation.coral, @area.observation, @area) %> |
					<%= link_to 'Back to observation', coral_observation_path(@area.observation.coral, @area.observation) %> |
					<%= link_to 'Back to coral', coral_path(@area.observation.coral) %>
				</p>
				</td>
			</tr>
		</table>


		<h2>Tagged colony observation area touches</h2>

		<table class='table table-condensed'>
		<tr>
			<th></th>
			<th>Touch number</th>
<!-- 			<th>Area ID</th>
			<th>Observation ID</th>
			<th>Coral ID</th>
 -->			<th>Outliner</th>
			<!-- <th>Outline filename</th> -->
			<th>Touch Length</th>
			<th>Taxon</th>
			<th>Growth form</th>
			<th>Interaction type</th>
			<!-- <th>Taxon ID</th> -->
			<th>Touch notes</th>
			<th width="150px"></th>
		</tr>

		<%= render @area.touches.sort_by{|e| e[:outline_filename]}  %>

		<tr style='background-color:white;'>
			<%= form_for([@area, @area.touches.build]) do |f| %>

			  <td></td>
			  <td><%= f.number_field :touch_number, :style=>'width: 50px;' %></td>
<!-- 			  <td><%#= @area.id %></td>
			  <td><%#= @area.observation_id %></td>
			  <td><%#= @area.observation.coral_id %></td>
 -->			  <td><%= f.text_field :outliner_name, :style=>'width: 70px;' %></td>
			  <!-- <td><%#= f.text_field :outline_filename, :style=>'width: 150px;', :value=> @area.outline_filename + '_' + @area.outliner_name + '.cp' %></td> -->
			  <td><%= f.number_field :length, :style=>'width: 80px;' %></td>
			  <td><%= f.select :taxon1, ['', 'Acropora', 'Montipora', 'Isopora', 'Pocilloporid', 'Poritid', 'Favid', 'Mussid', 'Other hard coral', 'Soft coral', 'Fleshy macroalga', 'Erect calcareous macroalga', 'Hydrocoral', 'Hydroid', 'Uncertain'] %></td>
			  <td><%= f.select :growth_form, ['', 'Massive', 'Branching', 'Corymbose', 'Cuneiform', 'Encrusting', 'Tabular', 'Digitate', 'Foliose', 'Non-coral', 'Uncertain'] %></td>
			  <td><%= f.select :touch_type, ['', 'Digested', 'Digesting', 'Mutual digestion', 'Overtopped', 'Overtopping', 'Overgrown', 'Overgrowing', 'Other direct contact', 'Uncertain'] %></td>
			  <!-- <td><%#= f.select :taxon2, ['', 'TBD'] %></td> -->
			  <td><%= f.text_field :notes, :style=>'width: 200px;' %></td>

			  <td><%= f.submit %></td>
			<% end %>
		</tr>
		</table>
		<p id="notice"><%= notice %></p>
		<br/>

	</div>
</div>