config/routes.rb
Trimodal::Application.routes.draw do

  resources :contributors

  resources :fecund_corals

  resources :ss_corals

  resources :spawners

  resources :touches

  resources :people do
    resources :spawners
  end

  resources :fieldtrips do
    resources :observations
    resources :spawners
    resources :ss_corals
    resources :fecund_corals
  end

  resources :observations do
    resources :areas
  end

  resources :areas do
    resources :touches
  end

  resources :corals do
    resources :observations do
      resources :areas do
        resources :touches
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'contributors#new',      via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'


  # match 'export_touches' => 'corals#export_tagged', via: 'get'
  match 'export_tagged' => 'corals#export_tagged', via: 'get'
  match 'export_corals' => 'corals#export_corals', via: 'get'
  match 'export_spawners' => 'spawners#export_spawners', via: 'get'
  match 'export_size_structure' => 'ss_corals#export_size_structure', via: 'get'
  match 'export_fecundity' => 'fecund_corals#export_fecundity', via: 'get'

end

app/models/touch.rb
class Touch < ActiveRecord::Base
  validates :touch_number, :numericality => { :greater_than => 0 }, :on => :create
  
  belongs_to :area
end

app/controllers/touches_controller.rb
class TouchesController < ApplicationController
  before_action :signed_in_contributor
  # GET /touches
  # GET /touches.json
  def index

    @coral = Coral.find(params[:coral_id])
    @observation = Observation.find(params[:observation_id])
    @area = Area.find(params[:area_id])

    @touches = @area.touches.find(params[:area_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @touches }
    end
  end


  # def export
      
  #   if signed_in?
  #     @touches = Touch.joins{measurements}.where{measurements.trait_id.in my{params[:checked]}}
  #   end        
    
  #   csv_string = CSV.generate do |csv|
  #     csv << ["observation_id", "access", "enterer", "coral", "location_name", "latitude", "longitude", "resource_id", "measurement_id", "trait_name", "standard_unit", "value", "precision", "precision_type", "precision_upper", "replicates"]
  #     @observations.each do |obs|
  #       if params[:global].blank? || obs.location_id == 1
  #         obs.measurements.each do |mea|
  #           if !params[:ancillary].blank? | params[:checked].include?(mea.trait_id.to_s)
  #             if obs.location.present?
  #               loc = obs.location.location_name
  #               lat = obs.location.latitude
  #               lon = obs.location.longitude
  #               if obs.location.id == 1
  #                 lat = ""
  #                 lon = ""
  #               end
  #             else
  #               loc = ""
  #               lat = ""
  #               lon = ""
  #             end
  #             if obs.private == true
  #               acc = 0
  #             else
  #               acc = 1
  #             end
  #             csv << [obs.id, acc, obs.user_id, obs.coral.coral_name, loc, lat, lon, obs.resource_id, mea.id, mea.trait.trait_name, mea.standard.standard_unit, mea.value, mea.precision, mea.precision_type, mea.precision_upper, mea.replicates]
  #           end
  #         end
  #       end
        
  #     end
  #   end

  #   send_data csv_string, 
  #     :type => 'text/csv; charset=iso-8859-1; header=present', :stream => true,
  #     :disposition => "attachment; filename=ctdb_#{Date.today.strftime('%Y%m%d')}.csv"
          
  # end





  # GET /touches/1
  # GET /touches/1.json
  def show

    @touch = Touch.find(params[:id])

    @area = Area.find(params[:area_id])
    @observation = Observation.find(params[:observation_id])
    @coral = Coral.find(params[:coral_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @touch }
    end
  end

  # GET /touches/new
  # GET /touches/new.json
  def new

    @coral = Coral.find(params[:coral_id])
    @observation = Observation.find(params[:observation_id])
    @area = Area.find(params[:area_id])
    @touch = @area.touches.create(params[:touch])


    # @touch = Touch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @touch }
    end
  end

  # GET /touches/1/edit
  def edit

    # @observation = Observation.find(params[:observation_id])
    @area = Area.find(params[:area_id])
    @touch = @area.touches.find(params[:id])


    # @touch = Touch.find(params[:id])
  end

  # POST /touches
  # POST /touches.json
  def create

    @area = Area.find(params[:area_id])
    @touch = @area.touches.create(touch_params)

    # @touch = Touch.new(params[:touch])

    # respond_to do |format|
    #   if @touch.save
    #     format.html { redirect_to @touch, notice: 'Touch was successfully created.' }
    #     format.json { render json: @touch, status: :created, location: @touch }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @touch.errors, status: :unprocessable_entity }
    #   end
    # end


    # @observation = Observation.find(params[:observation_id])
    # @area = @observation.areas.create(params[:area])

    respond_to do |format|
      if @area.save
        format.html { redirect_to coral_observation_area_path(@area.observation.coral, @area.observation, @area), notice: 'The area was successfully created.' }
        format.json { render json: @area, status: :created, location: @area }
      else
        format.html { redirect_to coral_observation_area_path(@area.observation.coral, @area.observation, @area), notice: '*The touch was NOT created.  You must enter a unique and positive touch number corresponding with your touch points.' }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end



  end

  # PUT /touches/1
  # PUT /touches/1.json
  def update
    @touch = Touch.find(params[:id])

    respond_to do |format|
      if @touch.update_attributes(touch_params)
        format.html { redirect_to coral_observation_area_path(@touch.area.observation.coral, @touch.area.observation, @touch.area), notice: 'Touch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @touch.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /touches/1
  # DELETE /touches/1.json
  def destroy
    # @observation = Observation.find(params[:observation_id])
    @area = Area.find(params[:area_id])
    @touch = @area.touches.find(params[:id])


    # @touch = Touch.find(params[:id])
    @touch.destroy

    respond_to do |format|
      format.html { redirect_to coral_observation_area_path(@area.observation.coral, @area.observation, @area), notice: 'Area was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
  
  def touch_params
    params.require(:touch).permit(:area_id, :outliner_name, :outline_filename, :taxon1, :taxon2, :touch_type, :length, :flag, :notes, :touch_number, :growth_form)
  end

  # t.integer  "area_id"
  # t.string   "outliner_name"
  # t.string   "outline_filename"
  # t.string   "taxon1"
  # t.string   "taxon2"
  # t.string   "touch_type"
  # t.decimal  "length"
  # t.boolean  "flag"
  # t.text     "notes"
  # t.datetime "created_at",       :null => false
  # t.datetime "updated_at",       :null => false
  # t.integer  "touch_number"
  # t.string   "growth_form"

end

app/helpers/touches_helper.rb
module TouchesHelper
end

app/views/touches/_form.html.erb
<%= form_for(@touch) do |f| %>
  <% if @touch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@touch.errors.count, "error") %> prohibited this touch from being saved:</h2>

      <ul>
      <% @touch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :area %><br />
    <%= @touch.area_id %>
    <!-- <%= f.text_field :area %> -->
  </div>
  <div class="field">
    <%= f.label :outliner_name %><br />
    <%= f.text_field :outliner_name %>
  </div>
  <div class="field">
    <%= f.label :outline_filename %><br />
    <%= f.text_field :outline_filename %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.text_field :length %>
  </div>
  <div class="field">
    <%= f.label :taxon1 %><br />
	<%= f.select :taxon1, ['', 'Acropora', 'Montipora', 'Isopora', 'Pocilloporid', 'Poritid', 'Favid', 'Mussid', 'Other hard coral', 'Soft coral', 'Fleshy macroalga', 'Erect calcareous macroalga', 'Hydrocoral', 'Hydroid', 'Uncertain'] %>
  </div>
  <div class="field">
    <%= f.label :growth_form %><br />
    <%= f.select :growth_form, ['', 'Massive', 'Branching', 'Corymbose', 'Cuneiform', 'Encrusting', 'Tabular', 'Digitate', 'Foliose', 'Non-coral', 'Uncertain'] %>
  </div>
  <div class="field">
    <%= f.label :touch_type %><br />
	<%= f.select :touch_type, ['', 'Digested', 'Digesting', 'Mutual digestion', 'Overtopped', 'Overtopping', 'Overgrown', 'Overgrowing', 'Other direct contact', 'Uncertain'] %>
  </div>
  <div class="field">
    <%= f.label :taxon2 %><br />
	<%= f.select :taxon2, ['', 'TBD'] %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/touches/_touch.html.erb
<tr>
	<td>Touch:</td>
	<td><%= touch.touch_number %></td>
<!-- 	<td><%#= touch.area_id %></td>
	<td><%#= touch.area.observation_id %></td>
	<td><%#= touch.area.observation.coral_id %></td>
 -->	<td><%= touch.outliner_name %></td>
	<!-- <td><%#= link_to touch.outline_filename, @file_path + 'tagged_touch_files/' + touch.outline_filename %></td> -->
	<td><% if !touch.length.blank? %><%= '%.2f' % touch.length %><% end %></td>
	<td><%= touch.taxon1 %></td>
	<td><%= touch.growth_form %></td>
	<td><%= touch.touch_type %></td>
	<!-- <td><%#= touch.taxon2 %></td> -->
	<td><%= touch.notes %></td>

  <td>
    <div class="btn-group">
      <%= link_to 'Edit', edit_coral_observation_area_touch_path(touch.area.observation.coral, touch.area.observation, touch.area, touch), class: "btn btn-default" %>
      <%= link_to 'Delete', coral_observation_area_touch_path(touch.area.observation.coral, touch.area.observation, touch.area, touch), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-danger" %>
    </div>
  </td>

</tr>

app/views/touches/edit.html.erb
<h1>Editing touch</h1>

<%= render 'form' %>

app/views/touches/index.html.erb
<h1>Listing touches</h1>

<table>
  <tr>
    <th>Area</th>
    <th>Outliner name</th>
    <th>Outline filename</th>
    <th>Taxon1</th>
    <th>Taxon2</th>
    <th>Type</th>
    <th>Length</th>
    <th>Flag</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @touches.each do |touch| %>
  <tr>
    <td><%= touch.area %></td>
    <td><%= touch.outliner_name %></td>
    <td><%= touch.outline_filename %></td>
    <td><%= touch.taxon1 %></td>
    <td><%= touch.taxon2 %></td>
    <td><%= touch.type %></td>
    <td><%= touch.length %></td>
    <td><%= touch.flag %></td>
    <td><%= touch.notes %></td>
    <td><%= link_to 'Show', touch %></td>
    <td><%= link_to 'Edit', edit_touch_path(touch) %></td>
    <td><%= link_to 'Destroy', touch, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Touch', new_touch_path %>

app/views/touches/new.html.erb
<h1>New touch</h1>

<%= render 'form' %>

<%= link_to 'Back', touches_path %>

app/views/touches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Area:</b>
  <%= @touch.area %>
</p>

<p>
  <b>Outliner name:</b>
  <%= @touch.outliner_name %>
</p>

<p>
  <b>Outline filename:</b>
  <%= @touch.outline_filename %>
</p>

<p>
  <b>Taxon1:</b>
  <%= @touch.taxon1 %>
</p>

<p>
  <b>Taxon2:</b>
  <%= @touch.taxon2 %>
</p>

<p>
  <b>Type:</b>
  <%= @touch.type %>
</p>

<p>
  <b>Length:</b>
  <%= @touch.length %>
</p>

<p>
  <b>Flag:</b>
  <%= @touch.flag %>
</p>

<p>
  <b>Notes:</b>
  <%= @touch.notes %>
</p>


<%= link_to 'Edit', edit_touch_path(@touch) %> |
<%= link_to 'Back', touches_path %>