config/routes.rb
Trimodal::Application.routes.draw do

  resources :contributors

  resources :fecund_corals

  resources :ss_corals

  resources :spawners

  resources :touches

  resources :people do
    resources :spawners
  end

  resources :fieldtrips do
    resources :observations
    resources :spawners
    resources :ss_corals
    resources :fecund_corals
  end

  resources :observations do
    resources :areas
  end

  resources :areas do
    resources :touches
  end

  resources :corals do
    resources :observations do
      resources :areas do
        resources :touches
      end
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'contributors#new',      via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'


  # match 'export_touches' => 'corals#export_tagged', via: 'get'
  match 'export_tagged' => 'corals#export_tagged', via: 'get'
  match 'export_corals' => 'corals#export_corals', via: 'get'
  match 'export_spawners' => 'spawners#export_spawners', via: 'get'
  match 'export_size_structure' => 'ss_corals#export_size_structure', via: 'get'
  match 'export_fecundity' => 'fecund_corals#export_fecundity', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-43657135-1', 'coraltraits.org');
	  ga('send', 'pageview');

	</script>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-inverse" role="navigation">
	  <div class="container-fluid">

	    <div class="navbar-header">

	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

				<ul class="nav navbar-nav navbar-left">
					<li><%= link_to "Home", root_path %></li>
				</ul>
		
			  <% if signed_in? %>
					<ul class="nav navbar-nav navbar-left">
			    <li id="fat-menu" class="dropdown">
			       <a href="#" class="dropdown-toggle" data-toggle="dropdown">
			         Data<b class="caret"></b>
			       </a>
			       <ul class="dropdown-menu" style="text-align: left;">
			         <li><%= link_to "Fieldtrips", fieldtrips_path %></li>
			         <li><%= link_to "Tagged corals", corals_path %></li>
			         <li><%= link_to "Fecundity", fecund_corals_path %></li>
			         <li><%= link_to "Spawners", spawners_path %></li>
			         <li><%= link_to "Size structure", ss_corals_path %></li>
					     <li class="divider"></li>
							 <li><%= link_to "Help", help_path %></li>
			       </ul>
			     </li>
					</ul>
			  <% end %>

				<ul class="nav navbar-nav navbar-right">
					<% if signed_in? %>
					  <li id="fat-menu" class="dropdown" style="text-align: left;">
					    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
					      Account <b class="caret"></b>
					    </a>
					    <ul class="dropdown-menu">
					      <li><%= link_to "Profile", current_contributor %></li>
					      <li><%= link_to "Settings", edit_contributor_path(current_contributor) %></li>
								<% if current_contributor.admin? %>
					      	<li><%= link_to "New Contributor", signup_path %></li>
								<% end %>
					      <li class="divider"></li>
					      <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
					    </ul>
					  </li>
					<% else %>
					  <li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>

				<ul class="nav navbar-nav navbar-right">
				  <% if signed_in? && current_contributor.admin? %>
				    <li><%= link_to "Contributors", contributors_path %></li>
				  <% end %>
				</ul>
			</div>		
		</div>
	</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!-- <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trimodal</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>

			<footer>
      	<%= render 'layouts/footer' %>
      </footer>

      <%#= debug(params) if Rails.env.development? %>
		</div>
  </body>
</html>